### ISSUE TITLE
Feature request: optionally serve insight from /

### ISSUE THREAD

**Issue by hkparker** [bitpay/insight-website#96]
It would be great to be able to host a public instance of bitcore with insight, and be able to host insight on the root path via a configuration option, as opposed to /insight.

**Comment by bitjson** [comment]
Hey @hkparker – this repo is the public staging area for the [Insight public website: https://insight.is/](https://insight.is/). Would you mind opening this request to the [Insight repo](https://github.com/bitpay/insight-ui)? Thanks!

**Comment by hkparker** [comment]
That's what I was looking for -- thanks!
